<?php 
/**
 * Implements hook_menu().
 */
function module_new_menu() {
  $items = array();

    $items['new/%'] = array(
    'title' => 'new test',
    'page callback' => 'new_page',
        'page arguments' => array(1),        
    'access arguments' => array('access content'),
        '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'module_new') . '/sociall.js',
      ), ),
    //'file' => 'demo.extra.inc',
    //'weight' => 1,
  );

  return $items;
}
//function new_page() {
//  $items = array();
//
//  $items['magic'] = array(
//    'title' => 'A yyyyyyyyyyy little magic',
//    'page callback' => 'menu_magic_basic55',
//    'access arguments' => array('access content'),
//  );
//
//  return $items;
//}


function new_page() {
    $path = 'http://dev-preview2site.gotpantheon.com/';
    $path .= current_path();
    
    
   
  $content = array(
      
    '#type' => 'markup',
    '#markup' =>  '<div class="fb-share-button" data-href="'.$path.'" data-type="button_count"></div>llllll',
    //  'page callback' => 'social',
      );
  
  $path = current_path();
  return $content;
}
//function social(){
//  <div id="fb-root"></div>
//<script>(function(d, s, id) {
//  var js, fjs = d.getElementsByTagName(s)[0];
//  if (d.getElementById(id)) return;
//  js = d.createElement(s); js.id = id;
//  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=576269352410010";
//  fjs.parentNode.insertBefore(js, fjs);
//}(document, 'script', 'facebook-jssdk'));</script>  
//}



//function menu_magic_menu() {
//  $items = array();
//
//  $items['magic'] = array(
//    'title' => 'A little dfbmagic',
//    'page callback' => 'menu_magic_basic',
//    'access arguments' => array('access content'),
//  );
//    $items['magic2'] = array(
//    'title' => 'A little magic',
//    'page callback' => 'menu_magic_basic2',
//    'access arguments' => array('access content'),
//  );
//
//  $items['magic/%'] = array(
//    'title' => 'Even more magical',
//    'page callback' => 'menu_magic_extra',
//    'page arguments' => array(1),
//    'access arguments' => array('access content'),
//    'file' => 'menu_magic.extra.inc',
//  );
//
//  $items['user/%/magic'] = array(
//    'title' => 'Magic',
//    'description' => 'Magical magic for users',
//    'page callback' => 'menu_magic_user_tab',
//    'page arguments' => array(1),
//    'access callback' => 'user_access',
//    'access arguments' => array('administer users'),
//    'file' => 'menu_magic.user.inc',
//    'type' => MENU_LOCAL_TASK,
//  );
//
//  // node_load(%)
//  $items['node/%node/magic'] = array(
//    'title' => 'Magic',
//    'description' => 'Do amazing and magical things',
//    'page callback' => 'menu_magic_node_context',
//    'page arguments' => array(1),
//    'access arguments' => array('access content'),
//    'file' => 'menu_magic.context.inc',
//    'type' => MENU_LOCAL_TASK,
//    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
//  );
//
//  return $items;
//}
//
//function menu_magic_basic() {
//  $content = array();
//
//  // This is a very, very simple page element. It will appear on the page,
//  // but other modules can't customize it and themes can't override its markup.
//  $content['raw_markup'] = array(
//    '#type' => 'markup',
//    '#markup' => 'Truly, this is magical!',
//    '#prefix' => '<p>',
//    '#suffix' => '</p>',
//  );
//
//  $variables = array(
//    'path' => 'http://placekitten.com/440/400',
//    'alt' => t('This is a magical kitten'),
//    'title' => t('This is the title'),
//  );
//  $content['themed_data'] = array(
//    '#type' => 'markup',
//    '#markup' => theme('image', $variables),
//    '#prefix' => '<div class="menu-magic-image">',
//    '#suffix' => '</div>',
//    '#attached' => array(
//      'css' => array(
//        drupal_get_path('module', 'menu_magic') . '/menu_magic.css',
//      ),
//    ),
//  );
//
//  $content['renderable_element'] = array(
//    '#theme' => 'item_list',
//    '#title' => t('How do we know it\'s magic?'),
//    '#items' => array(
//      t("Is it made of wood?"),
//      t("Does it sink in water?"),
//      t("Does it weigh the same as a duck?"),
//      t('The current time is %time.', array('%time' => date('r'))),
//    ),
//    '#cache' => array(
//      'keys' => array('menu_magic', 'renderable_element'), // menu_magic:renderable_element
//      'bin' => 'cache',
//      'expire' => time() + 30,
//      'granularity' => DRUPAL_CACHE_PER_PAGE,
//    ),
//  );
//
//  return $content;
//}
//
//
//
//
//
//
//







