<?php


/**
 * Implements hook_node_info().
 */
function demotour_node_info() {
	//   variable_set('language_content_type_slideshow', 2);
	return array(
    'demotour' => array(
      'name' => t('Demo turas'),
      'base' => 'demotour',
      'description' => t('Demo turo puslapis.'),
      'has_title' => TRUE,
      'has_body' => TRUE,
      'title_label' => t('Title'),
      'locked' => TRUE,
	)
	);
}

function demotour_menu(){
	$items['demo-turas'] = array(
    'title' => 'Demo turas',
    'page callback' => 'demotour_page_list',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
	);

	return $items;
}

/**
 * Implements hook_field_extra_fields().
 */
function demotour_field_extra_fields() {
	$extra['node']['demotour'] = array(
    'form' => array(
      'body' => array(
        'label' => t('Body'),
        'description' => t('Body'),
        'weight' => 1,
	),
	),
    'display' => array(
      'title' => array(
        'label' => t('Title'),
        'description' => t('The name of the demotour'),
        'weight' => 0,
	),
      'body' => array(
        'label' => t('Body'),
        'description' => t('The body of the demotour'),
        'weight' => 0,
	),
	),
	);
	return $extra;
}



/**
 * Implements hook_form().
 */
function demotour_form($node, &$form_state) {
	global $user;
	$admin = user_access('bypass demotour access') || user_access('edit any demotour content') || (user_access('edit own demotour content') && $user->uid == $node->uid);

	$form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Pavadinimas'),
    '#default_value' => !empty($node->title) ? $node->title : '',
    '#required' => TRUE,
    '#weight' => 0,
	);

	return $form;
}


/**
 * Implements hook_node_view().
 */
function demotour_view($node, $view_mode){
	global $language;

	$current_page = (isset($_GET['page']) ? $_GET['page'] : 0);

	$body = $node->body[$language->language]['0']['value'];

	$pages = explode('<!--pagebreak-->', $body);

	if(empty($pages[$current_page])){ $current_page = 0; }

	if(demotour_isajax()){

		$node->content['title'] = array(
      '#markup' => '<h1 class="title" id="page-title">'.$node->title.'</h1>',
      '#weight' => -50,
		);

		$node->content['more-tours'] = array(
      '#markup' => l(t('Kiti turai'), 'demo-turas', array(
          'attributes' => array(
              'class' => array('colorbox-inline', 'right'),
              'style' => array('margin-top: -25px;position: relative;margin-right: 35px;'),
		),
          'query' => array('width' => '700'),
		)),
      '#weight' => -20,
		);

	}
	$node->content['body'] = array(
    '#markup' => $pages[$current_page],
    '#weight' => 2,
	);


	if(($current_page - 1) >= 0){
		$node->content['previous'] = array(
      '#markup' => l(t('Atgal'), 'node/'.$node->nid, array(
          'attributes' => array(
            'class' => array('colorbox-inline', 'left', 'demotour-back')
		),
          'query' => array('width' => '700', 'page' => ($current_page - 1))
		)),
      '#weight' => 3,
		);
	}

	$node->content['step'] = array(
    '#markup' => '<div class="demotour-steps" style="margin: 0 auto; width: 100px; text-align: center;"><span>'.($current_page + 1).'</span>/'.count($pages).'</div>',
    '#weight' => 5,
	);

	if(!empty($pages[$current_page + 1])){
		$node->content['next'] = array(
      '#markup' => l(t('Pirmyn'), 'node/'.$node->nid, array(
        'attributes' => array(
          'class' => array('colorbox-inline', 'right', 'demotour-next')
		),
        'query' => array('width' => '700', 'page' => ($current_page + 1))
		)),
      '#weight' => 4,
		);
	}

	if(demotour_isajax()){
		echo $content = render($node->content);
		exit;
	}
	return $node;
}

function demotour_page_list(){

	drupal_set_title(t('Demo turas'));

	$nodes = demotour_list();

	$links = array();
	foreach($nodes as $node){
		$links[] = array(
      'title' => $node->title,
      'href'=> 'node/'.$node->nid,
      'attributes' => array(
        'class' => 'colorbox-inline',
		),
      'query' => array('width' => '700'),
		);
	}

	if(demotour_isajax()){
		$content[] = array(
      '#prefix' => '<h1 class="title" id="page-title">',
      '#markup' => t('Demo turas'),
      '#suffix' => '</h1>',
		);
	}

	$content[] = array(
    '#theme' => 'links',
    '#links' => $links,
    '#heading' => ' ',
	);

	if(demotour_isajax()){
		echo drupal_render($content);
		exit;
	}
	return $content;

}

function demotour_list() {
	global $language;
	$nids = db_select('node', 'n')
	->addTag('node_access')
	->fields('n', array('nid', 'nid'))
	->condition('type', 'demotour')
	->condition('language', $language->language)
	->condition('status', 1)
	->orderBy('created', 'ASC')
	->execute()
	->fetchAllKeyed();
	$nodes = node_load_multiple($nids);
	return $nodes;
}

function demotour_isajax(){
	if (isset($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest' ) {
		return true;
	}
	return false;
}
